-- Advanced features patch applied
ALTER TABLE users ADD COLUMN IF NOT EXISTS login_attempts INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until DATETIME NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_ip VARBINARY(16) NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_path VARCHAR(512) NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_mime VARCHAR(128) NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_size INT UNSIGNED NULL;
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS last_page VARCHAR(255) NULL;
